# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
x= s.split(" ")
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
str= "The diameter of {planet} is {diameter} kilometers".format(planet=planet, diameter=diameter)
print(str)

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [18]:
d= {'age':[22,33,44] , 'salary':[100,2000,3000]}
dataframe=pd.DataFrame(d)
dataframe

age  salary
0   22     100
1   33    2000
2   44    3000

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
df=pd.DataFrame()
df['time']= pd.date_range(start="1/1/2023", end="2/10/2023", freq='24H')
df['year']= df['time'].dt.year
df['month']= df['time'].dt.day
df['day']= df['time'].dt.day
df.head(len(df["time"]))

time  year  month  day
0  2023-01-01  2023      1    1
1  2023-01-02  2023      2    2
2  2023-01-03  2023      3    3
3  2023-01-04  2023      4    4
4  2023-01-05  2023      5    5
5  2023-01-06  2023      6    6
6  2023-01-07  2023      7    7
7  2023-01-08  2023      8    8
8  2023-01-09  2023      9    9
9  2023-01-10  2023     10   10
10 2023-01-11  2023     11   11
11 2023-01-12  2023     12   12
12 2023-01-13  2023     13   13
13 2023-01-14  2023     14   14
14 2023-01-15  2023     15   15
15 2023-01-16  2023     16   16
16 2023-01-17  2023     17   17
17 2023-01-18  2023     18   18
18 2023-01-19  2023     19   19
19 2023-01-20  2023     20   20
20 2023-01-21  2023     21   21
21 2023-01-22  2023     22   22
22 2023-01-23  2023     23   23
23 2023-01-24  2023     24   24
24 2023-01-25  2023     25   25
25 2023-01-26  2023     26   26
26 2023-01-27  2023     27   27
27 2023-01-28  2023     28   28
28 2023-01-29  2023     29   29
29 2023-01-30  2023     30   30
30 2023-01-31  2023     31   31
31 2023-02-01  2023      1    1
32 2023-02-02  2023      2    2
33 2023-02-03  2023      3    3
34 2023-02-04  2023      4    4
35 2023-02-05  2023      5    5
36 2023-02-06  2023      6    6
37 2023-02-07  2023      7    7
38 2023-02-08  2023      8    8
39 2023-02-09  2023      9    9
40 2023-02-10  2023     10   10

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [21]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [22]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24